

name: Test sarif

on:
  workflow_dispatch:

jobs:
  container_scan_job:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Scan Container Image
        id: orcasecurity
        uses: ./
        with:
          api_token:
            ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key:
            "default"
          image:
            "redis:5.0.6"
          format:
            "json,sarif"
          output:
            "results/"
          console_output: "table"
      - name: print results
        if: always()
        run: |
          echo ${{ steps.orcasecurity.outputs.finished }}
          echo ${{ steps.orcasecurity.outputs.finished == 'true' }}
      - uses: actions/upload-artifact@v3
        if: ${{ steps.orcasecurity.outputs.finished == 'true' }}
        with:
          name: orca-results
          path: results/
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if:   always() && steps.orcasecurity.outputs.finished == 'true'
        with:
          sarif_file: results/image.sarif
