name: Test sarif

on:
  workflow_dispatch:

jobs:
  container_scan_job:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Scan Container Image
        id: orcasecurity
        uses: ./
        with:
          api_token:
            ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key:
            "default"
          image:
            "alpine:3"
          format:
            "json,sarif"
          output:
            "results/"
          console_output: "table"
     
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() && steps.orcasecurity.outputs.exit_code != 1 }}
        with:
          sarif_file: results/image.sarif
